---
- name: Static Page
  hosts: g1
  become: yes

  tasks:
    - name: Ensure /var/www/html directory exists
      file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Update static page
      copy:
        src: files/static.html
        dest: /var/www/html/static.html
        mode: '0644'
...