---
    - name: Update static page
      copy:
        src: files/static.html
        dest: /var/www/html/static.html
        mode: '0644'

    - name: Update static page
      template:
        src: dynamic.j2
        dest: /var/www/html/dynamic.html
...